# Generated by Django 3.2.15 on 2023-02-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
                ('place_lon', models.FloatField(null=True, verbose_name='Долгота')),
                ('place_lat', models.FloatField(null=True, verbose_name='Широта')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='Последнее обновление')),
            ],
        ),
    ]
