# Generated by Django 3.2.15 on 2022-11-21 14:59

from django.db import migrations

def set_price_for_old_orders(apps, schema_editor):
    OrderElement = apps.get_model('foodcartapp', 'OrderElement')
    for element in OrderElement.objects.all():
        element.element_price = element.product.price
        element.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20221121_1257'),
    ]

    operations = [
        migrations.RunPython(set_price_for_old_orders),
    ]
