# Generated by Django 3.2.15 on 2022-11-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20221121_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Creted'), ('CK', 'Cooking'), ('DL', 'Delivery'), ('DN', 'Done')], default='CR', max_length=2),
        ),
    ]
