# Generated by Django 3.2.15 on 2022-11-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20221121_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('ON', 'Онлайн')], default='CH', max_length=2),
        ),
    ]
