# Generated by Django 3.2.15 on 2022-12-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20221204_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderelement',
            old_name='element_price',
            new_name='price',
        ),
    ]
