# Generated by Django 3.2.15 on 2022-12-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_rename_element_price_orderelement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderelements', to='foodcartapp.product', verbose_name='продукт'),
        ),
    ]
