# Generated by Django 3.2.15 on 2022-12-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20221204_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='cooking_restaurant',
        ),
    ]
