# Generated by Django 3.2.15 on 2022-12-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_rename_restaurant_order_cooking_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Карта'), ('ON', 'Онлайн')], max_length=2),
        ),
    ]
